library(testthat)
source("ValidateData.R")

context("Test funcIsValid")
test_that("NA and NUll are false, all others are true",{
  expect_equal(funcIsValid(NA),FALSE)
  expect_equal(funcIsValid(NULL),FALSE)
  expect_equal(funcIsValid(1), TRUE)
  expect_equal(funcIsValid("3"), TRUE)
  expect_equal(funcIsValid(c("3","4")), TRUE)
  expect_equal(funcIsValid(c(3,NA)), TRUE)
  expect_equal(funcIsValid(""), TRUE)
  expect_equal(funcIsValid(list()), TRUE)
  expect_equal(funcIsValid(2.3), TRUE)
  expect_equal(funcIsValid(TRUE), TRUE)
  expect_equal(funcIsValid(FALSE), TRUE)
  expect_equal(funcIsValid(as.factor(3)), TRUE)
})

context("Test funcIsValidString")
test_that("Test only strings are true",{
  expect_equal(funcIsValidString(NA),FALSE)
  expect_equal(funcIsValidString(NULL),FALSE)
  expect_equal(funcIsValidString(1), FALSE)
  expect_equal(funcIsValidString("3"), TRUE)
  expect_equal(funcIsValidString(c("3","4")), FALSE)
  expect_equal(funcIsValidString(""), TRUE)
  expect_equal(funcIsValidString(list()), FALSE)
  expect_equal(funcIsValidString(2.3), FALSE)
  expect_equal(funcIsValidString(TRUE), FALSE)
  expect_equal(funcIsValidString(FALSE), FALSE)
})

context("Test funcIsValidFileName")
strFileSimpleRCFileAnswer = file.path(c_strTestingDirectory,c_strCorrectAnswers,"FuncWriteMatrixToReadConfigFile_SimpleAnswer.read.config")
strFileUseAllRCFileAnswer = file.path(c_strTestingDirectory,c_strCorrectAnswers,"FuncWriteMatrixToReadConfigFile_AllAnswer.read.config")

test_that("Test only strings pointing to existing files are true",{
  expect_equal(funcIsValidFileName(NA),FALSE)
  expect_equal(funcIsValidFileName(NULL),FALSE)
  expect_equal(funcIsValidFileName(1), FALSE)
  expect_equal(funcIsValidFileName("3"), FALSE)
  expect_equal(funcIsValidFileName(c("3","4")), FALSE)
  expect_equal(funcIsValidFileName(""), FALSE)
  expect_equal(funcIsValidFileName(list()), FALSE)
  expect_equal(funcIsValidFileName(2.3), FALSE)
  expect_equal(funcIsValidFileName(TRUE), FALSE)
  expect_equal(funcIsValidFileName(FALSE), FALSE)
  expect_equal(funcIsValidFileName(strFileSimpleRCFileAnswer),TRUE)
  expect_equal(funcIsValidFileName(strFileUseAllRCFileAnswer),TRUE)
})

vVector1 = c(1,2,3)
vVector2 = c(11,22,33)
vVector3 = c(111,222,333)
mtrxMatrix = as.matrix(cbind(vVector1,vVector2,vVector3))
dfDataFrame = as.data.frame(mtrxMatrix)

context("Test funcIsValidMatrix")
test_that("Test only matrices are treu",{
  expect_equal(funcIsValidMatrix(NA),FALSE)
  expect_equal(funcIsValidMatrix(NULL),FALSE)
  expect_equal(funcIsValidMatrix(1), FALSE)
  expect_equal(funcIsValidMatrix("3"), FALSE)
  expect_equal(funcIsValidMatrix(TRUE), FALSE)
  expect_equal(funcIsValidMatrix(FALSE), FALSE)
  expect_equal(funcIsValidMatrix(TRUE), FALSE)
  expect_equal(funcIsValidMatrix(vVector1), FALSE)
  expect_equal(funcIsValidMatrix(mtrxMatrix), TRUE)
  expect_equal(funcIsValidMatrix(dfDataFrame), FALSE)
})

context("Test funcIsValidVector")
test_that("Test only vectors are true",{
  expect_equal(funcIsValidVector(NA),FALSE)
  expect_equal(funcIsValidVector(NULL),FALSE)
  expect_equal(funcIsValidVector(1), FALSE)
  expect_equal(funcIsValidVector("3"), FALSE)
  expect_equal(funcIsValidVector(TRUE), FALSE)
  expect_equal(funcIsValidVector(FALSE), FALSE)
  expect_equal(funcIsValidVector(TRUE), FALSE)
  expect_equal(funcIsValidVector(vVector1), TRUE)
  expect_equal(funcIsValidVector(mtrxMatrix), FALSE)
  expect_equal(funcIsValidVector(dfDataFrame), FALSE)
})

context("Test funcIsValidDataFrame")
test_that("TEst only data frames are true",{
  expect_equal(funcIsValidDataFrame(NA),FALSE)
  expect_equal(funcIsValidDataFrame(NULL),FALSE)
  expect_equal(funcIsValidDataFrame(1), FALSE)
  expect_equal(funcIsValidDataFrame("3"), FALSE)
  expect_equal(funcIsValidDataFrame(TRUE), FALSE)
  expect_equal(funcIsValidDataFrame(FALSE), FALSE)
  expect_equal(funcIsValidDataFrame(TRUE), FALSE)
  expect_equal(funcIsValidDataFrame(vVector1), FALSE)
  expect_equal(funcIsValidDataFrame(mtrxMatrix), FALSE)
  expect_equal(funcIsValidDataFrame(dfDataFrame), TRUE)
})