### Modifies labels for plotting
### astrNames Names to modify for plotting
funcRename <- function( astrNames )
{
  astrRet <- c()
  for( strName in astrNames )
  {
    astrName <- strsplit( strName, "\\|" )[[1]]
    i <- length( astrName )
    if( ( astrName[i] == "unclassified" ) || !is.na( as.numeric( astrName[i] ) ) )
    {
      strRet <- paste( astrName[( i - 1 ):i], collapse = "|" )
    } else {
    strRet <- astrName[i]
    }
    astrRet <- c(astrRet, strRet)
  }
  return( astrRet )
}

#Generates a given number of random colors
#@params tempNumberColors Number of colors to generate
funcGetRandomColors=function(tempNumberColors=1)
{
  adRet <- c()
  for(i in 1:tempNumberColors)
  {
    adRGB <- ( runif( 3 ) * 0.66 ) + 0.33
    adRet <- c(adRet, rgb( adRGB[1], adRGB[2], adRGB[3] ))
  }
  return(adRet)
}

funcColorHelper <- function( dMax = 1, dMin = -1, dMed = NA )
{
  if( dMax < dMin )
  {
    d <- dMax
    dMax <- dMin
    dMin <- d
  }
  if( is.na( dMed ) )
  {
    dMed <- ( dMin + dMax ) / 2
  }
  return( list( dMin = dMin, dMax = dMax, dMed = dMed ) ) }
	
funcColor <- function( dX, dMax = 1, dMin = -1, dMed = NA, adMax = c(1, 1, 0), adMin = c(0, 0, 1), adMed = c(0, 0, 0) )
{
  lsTmp <- funcColorHelper( dMax, dMin, dMed )
  dMax <- lsTmp$dMax
  dMin <- lsTmp$dMin
  dMed <- lsTmp$dMed
  if( is.na( dX ) )
  {
    dX <- dMed
  }
  if( dX > dMax )
  {
    dX <- dMax
  } else if( dX < dMin )
  {
    dX <- dMin }
  if( dX < dMed )
  {
    d <- ( dMed - dX ) / ( dMed - dMin )
    adCur <- ( adMed * ( 1 - d ) ) + ( adMin * d )
  } else {
    d <- ( dMax - dX ) / ( dMax - dMed )
    adCur <- ( adMed * d ) + ( adMax * ( 1 - d ) )
  }
  return( rgb( adCur[1], adCur[2], adCur[3] ) )
}

#funcColors <- function( dMax = 1, dMin = -1, dMed = NA, adMax = c(1, 1, 0), adMin = c(0, 0, 1), adMed = c(0, 0, 0), iSteps = 64 )
#{
#  lsTmp <- funcColorHelper( dMax, dMin, dMed )
#  dMax <- lsTmp$dMax
#  dMin <- lsTmp$dMin
#  dMed <- lsTmp$dMed
#  aRet <- c ()
#  for( dCur in seq( dMin, dMax, ( dMax - dMin ) / ( iSteps - 1 ) ) )
#  {
#    aRet <- c(aRet, funcColor( dCur, dMax, dMin, dMed, adMax, adMin, adMed ))
#  }
#  return( aRet )
#}

funcGetColor <- function( ) 
{
  adCol <- col2rgb( par( "col" ) )
  return( sprintf( "#%02X%02X%02X", adCol[1], adCol[2], adCol[3] ) )
}

#Remove whitespace at the beginning or the end of a string
#tempString String to be trimmed.
funcTrim=function(tempString)
{
  return(gsub("^\\s+|\\s+$","",tempString))
}

#Write a string or a table of data
#pOut String or table to write to file
#strFile String name of file
funcWrite <- function( pOut, strFile )
{
#  write( pOut, strFile, ncolumns = length( astrOut ), append = TRUE ) }
  if( length( intersect( class( pOut ), c("character", "numeric") ) ) )
  {
    write.table( t(pOut), strFile, quote = FALSE, sep = c_cTableDelimiter, col.names = FALSE, row.names = FALSE, na = "", append = TRUE )
  } else {
    capture.output( print( pOut ), file = strFile, append = TRUE )
  }
}

#Log a table to a file
#frmeTable Table to write
#strFile Log file
#fAppend Should appending occur.
funcWriteTable <- function( frmeTable, strFile, fAppend = FALSE )
{
  write.table( frmeTable, strFile, quote = FALSE, sep = c_cTableDelimiter, na = "", col.names = NA, append = fAppend )
}

funcFormat <- function( pValue ) {
	c_iMax	<- 8192

	strRet <- paste( format( pValue ), collapse = " " )
	if( nchar( strRet ) > c_iMax ) {
		strRet <- paste( substr( strRet, 0, c_iMax - 3 ), "...", sep = "" ) }
	return( strRet )
}

### Write out the quality control report
### strProcessFilename File name
### lsQCData List of QC data generated by maaslin to be written
### liDataDim Dimensions of the data matrix
### liMetadataDim Dimensions of the metadata matrix
funcWriteQCReport <- function(strProcessFileName, lsQCData, liDataDim, liMetadataDim)
{
  unlink(strProcessFileName)
  funcWrite( paste("Initial Metadata Matrix Size: Rows ",liMetadataDim[1],"  Columns ",liMetadataDim[2],sep=""), strProcessFileName )
  funcWrite( paste("Initial Data Matrix Size: Rows ",liDataDim[1],"  Columns ",liDataDim[2],sep=""), strProcessFileName )
  funcWrite( paste("\nInitial Data Count: ",length(lsQCData$aiDataInitial),sep=""), strProcessFileName )
  funcWrite( paste("Initial Metadata Count: ",length(lsQCData$aiMetadataInitial),sep=""), strProcessFileName )
  funcWrite( paste("Data Count after preprocess: ",length(lsQCData$aiAfterPreprocess),sep=""), strProcessFileName )
  funcWrite( paste("Removed for missing metadata: ",length(lsQCData$iMissingMetadata),sep=""), strProcessFileName )
  funcWrite( paste("Removed for missing data: ",length(lsQCData$iMissingData),sep=""), strProcessFileName )
  funcWrite( paste("Data with outliers: ",length(lsQCData$aiSumOutlierPerDatum[lsQCData$aiSumOutlierPerDatum>0]),sep=""), strProcessFileName )
  funcWrite( paste("Metadata count which survived clean: ",length(lsQCData$aiMetadataCleaned),sep=""), strProcessFileName )
  funcWrite( paste("Data count which survived clean: ",length(lsQCData$aiDataCleaned),sep=""), strProcessFileName )
  funcWrite( paste("\nBoostings: ",lsQCData$iBoosts,sep=""), strProcessFileName )
  funcWrite( paste("Boosting Errors: ",lsQCData$iBoostErrors,sep=""), strProcessFileName )
  funcWrite( paste("LMs with no terms suriving boosting: ",lsQCData$iNoTerms,sep=""), strProcessFileName )
  funcWrite( paste("LMs performed: ",lsQCData$iLms,sep=""), strProcessFileName )
  if(!is.null(lsQCData$lsQCCustom))
  {
    funcWrite("Custom preprocess QC data: ", strProcessFileName )
    funcWrite(lsQCData$lsQCCustom, strProcessFileName )
  } else {
    funcWrite("No custom preprocess QC data.", strProcessFileName )
  }
  funcWrite( "\n#Details###########################", strProcessFileName )
  funcWrite("\nInitial Data Count: ", strProcessFileName )
  funcWrite(lsQCData$aiDataInitial, strProcessFileName )
  funcWrite("\nInitial Metadata Count: ", strProcessFileName )
  funcWrite(lsQCData$aiMetadataInitial, strProcessFileName )
  funcWrite("\nData Count after preprocess: ", strProcessFileName )
  funcWrite(lsQCData$aiAfterPreprocess, strProcessFileName )
  funcWrite("\nRemoved for missing metadata: ", strProcessFileName )
  funcWrite(lsQCData$iMissingMetadata, strProcessFileName )
  funcWrite("\nRemoved for missing data: ", strProcessFileName )
  funcWrite(lsQCData$iMissingData, strProcessFileName )
  funcWrite("\nOutlier Count per Datum: ", strProcessFileName )
  funcWrite(lsQCData$aiSumOutlierPerDatum, strProcessFileName )
  funcWrite("\nMetadata which survived clean: ", strProcessFileName )
  funcWrite(lsQCData$aiMetadataCleaned, strProcessFileName )
  funcWrite("\nData which survived clean: ", strProcessFileName )
  funcWrite(lsQCData$aiDataCleaned, strProcessFileName )
}
